# Generated by Django 2.2.2 on 2019-08-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_operations_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operations',
            options={'verbose_name_plural': 'Operation'},
        ),
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name_plural': 'Report'},
        ),
    ]
