# Generated by Django 2.2.2 on 2019-08-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20190826_0545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
