# Generated by Django 2.2.2 on 2019-08-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
