# Generated by Django 2.2.2 on 2019-08-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20190826_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('cron_expression', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='calculator.Report')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedscheduledreport', to='calculator.ScheduledReport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportrecep', to='calculator.ScheduledReport')),
            ],
        ),
    ]
