# Generated by Django 2.2.2 on 2019-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20190828_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='action_parameter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
